### PR TITLE
Add option to log in with author address and password; add buttons to…

### PR DESCRIPTION
**Pull request by cinnamon-bun**
* Let users log in with their author address and secret
* Add buttons to copy those to the clipboard after loggin in, so they can be extracted and saved to a password manager
* Rewrite the help text in "Make a new identity"
* Move "sign out" button to its own `<section>` since it's not related to all the buttons about saving your identity

Screen Shot 2020-12-06 at 1 21 15 PM

Screen Shot 2020-12-06 at 1 21 23 PM

### CODE REVIEW

**Comment by sgwilym** [comment]
Tell me what you think about these thoughts:

1. The idea of using a file as a login is probably quite novel to most users, therefore clearly communicating how that system works is paramount.
2. That displaying both a form login and an upload login side-by-side is a bit of a cognitive overload for a user, let alone a new one.
3. My goal was to offer two different tabs: a `UserUploadTab` and `UserFormTab`, which client authors would be able to choose from and pass into `<Earthbar>`.  
4. Through this, I hoped we would be able to get a sense of what users bump into or like about either approach and be able to make more informed decisions from there about defaults or using one or the other.

I am still quite sceptical of the username and password UX. I understand the appeal to familiarity, but with that comes a user's expectations of what you can do with a username and password, which are usually wrong when applied to a keypair. They are superficially similar in having one public part and one secret part, but the similarities end there.

I could also warm up to having them together. Let's talk about it :)

**Comment by cinnamon-bun** [comment]
@sgwilym Thanks for the thoughtful feedback!

I've seen people having trouble with file-based login, and had trouble myself.  A developer said "I can't test my app on my iPhone because I don't know how to get my login file onto my phone and into the browser."  And I personally keep my keypair file in my password manager and I have to extract it unsafely onto the hard drive and use it from there; it's also a big pain on Android.  I can imagine file-based login working in some settings but for now I think it's reducing usability and security.

> I am still quite sceptical of the username and password UX.

I'm unsure if it should be called a "username" and "password"; in this version I called it "Author Address" and "secret" as an experiment.  I agree more user research is needed.

> My goal was to offer two different tabs, a `UserUploadTab` and `UserFormTab`

I like this idea.  Could we perhaps have a third one which includes both options?  Maybe the existing `UserTab` can be the "both" option, as it is in this PR, and another PR can add the individual versions?

As things are right now we're forcing everyone to use the file method without any other options, and it's really quite awkward to use in some scenarios, especially on phones.  Can we allow both methods as we continue to experiment?

**Comment by sgwilym** [comment]
@cinnamon-bun  I've been thinking about this and have a new idea.

Looking at the strengths and weaknesses of both approaches, a list of qualities for a way to store one's identity emerges:

1. It should be easy to save in a password manager
2. It can be copy and pasted (maybe this is just a reiteration of 1)
3. It does not suggest that it's a value you can regenerate or change (e.g. like a username/pass may suggest password can be reset)
4. It makes it clear that it is one indivisible unit, as public key and private key are useless without the other
5. It indicates the identity it relates to
5. It's hard to accidentally disclose through a screenshot or by looking over someone's shoulder

I think we can get to something nice with a subtle tweak. What if we compress the address and private key into a single string token, one which fulfils _all_ the qualities above?

Something like...

1. Derive the shortname from the address
2. Base64 the public address and private key together to obfuscate them (so as to make them useless in a screenshot)
3. Then build a new string like `{Base64edPubAndPrivateKey}{shortname}`

You save that single string in your password manager. When you want to authenticate with an Earthstar app, you paste it in, and it does the above process in reverse to reconstruct your keypair.

Some things I like about this:

- One value, disassociates it from username and passwords
- The shortname is appended to the end to hint at which identity this string is related to.
- The base64ing of the keys will make the string quite long, making it hard to screenshot or memorise if someone sees it offhand
- Easy to copy, paste, store safely

It's only slightly different to copying and pasting the JSON of the keypair, but maybe a tweak to that is what could make an approach like this good? Would love to hear your thoughts on this.

**Comment by cinnamon-bun** [comment]
@sgwilym 

Interesting idea!  Let's call this idea a "login code" for now.

Could we add this as **another option in a new PR** so app authors can choose and we can experiment with all 3?  I'd like to get this username-password PR merged in the meantime --  I don't want to get stuck trying to decide this without the ability to actually try them and do some user research.  We're still iterating, it won't be set in stone.

## Login code thoughts

Pros
* Meets all the criteria you listed which are all important, I won't repeat the whole list here :)
* Can't be confused with the author address -- don't want people to send it to friends by accident
* Doesn't feel like a username and password, so people won't make wrong assumptions about it
* Easier to copy-paste than JSON

Unmet needs
* Doesn't feel like a username and password, so there's more to learn and people might not get it.  Research is needed
* Password managers are easier to use if there's a "username" type of field to easily identify the account, otherwise you probably have to edit the title of the record by hand to indicate which account it is when you have several
* Users might also want to keep their original author address around so they can share it with people, and they can't extract it from a login code by themselves
* A user might have several different identities that all start with `@suzy`, so putting `@suzy` on the end isn't enough to know which one we're talking about, maybe we should include a few characters of the public key too
* base64 doesn't really protect it from screenshots since it's easy to decode, but it does prevent it from looking like an author address

Each of our 3 login methods have their own pros and cons, so it's possible this one is the best choice.  Or maybe it'll be important to support several methods, I'm not sure.

## Brainstorming some other formats for this

for author `@suzy.aaa` with secret `sss`

```ts
// your proposal plus a few chars of pubkey at the end
base64("@suzy.aaa:sss") + ":@suzy.aa"

// or in base32
base32("@suzy.aaa:sss") + ":@suzy.aa"

// or just put something on the front so it doesn't look like an author address.
// I also used "___" to help people see that there's a second part
"login:@suzy.aaa___sss"
```

Results, respectively:

* `QHN1enkuYmNrMnJsazcyamVvMnU0cTd0aG01NXFtenV4Y3Z6Zm91M2VzMnVqbnBkZWs1aTRkYnBwZnE6YmxhZXRncmJ3NnRqemlwd3V5NjdiaDVidGM2cGs3cnVkcmFtNTRydGxqa2p5NWVwNmp5bmE=:@suzy.bck2rl`

* `bibzxk6tzfzrgg2zsojwgwnzsnjsw6mtvgryto5dinu2tk4lnpj2xqy3wpjtg65jtmvzte5lknzygizllgvutizdcobygm4j2mjwgczlum5zge5zworvhu2lqo52xsnrxmjudkytumm3ha2zxoj2wi4tbnu2ti4tunrvgw2tzgvsxantkpfxgc:@suzy.bck2rl`

* `login:@suzy.bck2rlk72jeo2u4q7thm55qmzuxcvzfou3es2ujnpdek5i4dbppfq___blaetgrbw6tjzipwuy67bh5btc6pk7rudram54rtljkjy5ep6jyna`

## Encoding calculator

I made a little page to try out different encodings

https://tf6bd.csb.app/

https://codesandbox.io/s/base-32-and-base-64-calculator-tf6bd

**Comment by fwip** [comment]
Two probably bad ideas:

One interesting property that username/passwords have that "login codes" / tokens don't, is that the username & password have to "match." I don't think that this is a good idea, but we could replicate that by, say, encrypting the token with the "username" - and the site/app would use the two together to determine your real login token.

If we're messing around with encoding options, I'll throw [proquint](https://arxiv.org/html/0901.4016) on the pile. I forked your sandbox so you can see it in action: [https://codesandbox.io/s/base-32-and-base-64-calculator-forked-u8nkw].
The idea is that they are "human pronounceable", so if you need to, you can read them over the phone to another person more quickly.  Again, this might be a bad idea - secret tokens might not be the best place to emphasize readability. :P

Also a 3rd note, if part of the token is already something that has been base32 encoded, we might want to decode that part before re-encoding, to get a smaller token.

**Comment by cinnamon-bun** [comment]
Thanks @fwip !

You inspired me to add a few more including BIP39 recovery phrases (which are used by Manyverse) and some that decode the base32 first so we're not double-encoding anything.

https://dl98d.csb.app/

https://codesandbox.io/s/calculator-base32-base64-proquint-bip39-dl98d?file=/src/app.tsx

> the username & password have to "match." 

This brings to mind a few things
* It's possible to tell if a public and private key are a matching set.  (The private key is randomly generated, and then the public key is deterministically derived from the private key)
* If you mean does the 4-letter shortname match, I guess we could be a bit sloppy about that.  Users can change the shortname on a keypair as much as they want, it's not mathematically related to the keys, it just counts as a different user if you do that so I don't think it's a problem.  It would be weird if a login code had a different visible shortname vs. encoded shortname; I think we'd probably ignore the visible one?  Nobody but yourself should be handling your login codes so the opportunity for mischief is small

**Comment by cinnamon-bun** [comment]
Oops I just realized these can all be half as long...

We don't need to include the public key because it can be [deterministically derived from the private key](https://github.com/earthstar-project/earthstar/blob/master/src/crypto/cryptoChloride.ts#L27-L33).

https://qhsis.csb.app/

https://codesandbox.io/s/calculator-base32-base64-proquint-bip39-no-pubkey-qhsis?file=/src/app.tsx

**Comment by sgwilym** [comment]
@cinnamon-bun Great, I'm glad the idea is interesting!

Seeing as we're now going to have three different methods of logging in to play with, does this sound like a good way to wrap up this PR?

- Divide the current AuthorTab into a AuthorUploadTab, AuthorFormTab 
- UserPanel as you've changed it is used for both varieties, with buttons for keypair download and copying address and secret

**Comment by cinnamon-bun** [comment]
@sgwilym That sounds good, I'll make a second PR for the additional tab types if I have time today.

**Pull request merged**
